name: Fetch Album Art

on:
  schedule:
    - cron: '1 0 * * *' # Runs daily at 12:01 AM UTC
    - cron: '31 13 * * 4' # Runs on Thursdays at 1:31 PM UTC
  workflow_dispatch:

jobs:
  fetch-album-art:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all branches

    - name: Check out gh-pages branch
      run: |
        git checkout gh-pages

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and download album art
      run: |
        python fetch_album_art.py

    - name: Commit and push changes to gh-pages branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add album_art/ thumbnails/ instrument_icons/
        git commit -m 'Update album art, thumbnails, and instrument icons'
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}