name: Fetch Album Art

on:
  schedule:
    - cron: '5 0 * * 4' # Runs every Thursday at 7:05 PM EST (12:05 AM UTC on Friday)
  workflow_dispatch:

jobs:
  fetch-album-art:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and download album art
      run: |
        python fetch_album_art.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add album_art/
        git commit -m 'Update album art'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
